language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - SYMFONY_VERSION=2.1
  - SYMFONY_VERSION=2.2
  - SYMFONY_VERSION=2.3
  - SYMFONY_VERSION=2.4

before_script:
   - bash .travis.sh
   - wget http://getcomposer.org/composer.phar
   - php composer.phar install --prefer-source

script:
  - vendor/bin/phpunit --configuration phpunit.travis.xml
  - vendor/bin/php-cs-fixer

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.6
    - php: hhvm
